### ISSUE TITLE
Error when copying `.next/static/`

### ISSUE THREAD

**Issue by ehmicky** [netlify/next-on-netlify#102]
The [following build](https://app.netlify.com/sites/musing-williams-ddf07a/deploys/5fbe2f8513b0cd35556060e0) fails with:

```
────────────────────────────────────────────────────────────────
  Plugin "@netlify/plugin-nextjs" internal error                
────────────────────────────────────────────────────────────────

  Error message
  Error: ENOENT: no such file or directory, stat '.next/static'

  Plugin details
  Package:        @netlify/plugin-nextjs
  Version:        1.0.2
  Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
  npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
  Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues

  Error location
  In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
      at Object.statSync (fs.js:933:3)
      at Object.statSync (/opt/buildhome/.netlify-build-plugins/node_modules/graceful-fs/polyfills.js:307:34)
      at statSync (/opt/buildhome/.netlify-build-plugins/node_modules/fs-extra/lib/util/stat.js:10:52)
      at getStatsSync (/opt/buildhome/.netlify-build-plugins/node_modules/fs-extra/lib/util/stat.js:24:19)
      at Object.checkPathsSync (/opt/buildhome/.netlify-build-plugins/node_modules/fs-extra/lib/util/stat.js:49:33)
      at copySync (/opt/buildhome/.netlify-build-plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
      at copyNextAssets (/opt/buildhome/.netlify-build-plugins/node_modules/next-on-netlify/lib/steps/copyNextAssets.js:10:3)
      at nextOnNetlify (/opt/buildhome/.netlify-build-plugins/node_modules/next-on-netlify/index.js:25:3)
      at onBuild (/opt/buildhome/.netlify-build-plugins/node_modules/@netlify/plugin-nextjs/index.js:78:5)
      at async Object.run (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/run.js:19:3)
```

The problem seems to be there:

https://github.com/netlify/next-on-netlify/blob/42b1444fd54f1bd3c0e04b802ac3295a319473ba/lib/steps/copyNextAssets.js#L11

This specific build does not have a `.next/static/` directory, so trying to copy it fails.
I am not sure whether this is valid for `.next/static/` not to exist. If it is valid, then this function should not copy anything if `.next/static/` does not exist. If it is not valid, this function should throw with an error indicating the site has some configuration issues.

**Comment by mrpaulphan** [comment]
Has this been resolved? I'm also having the exact same issue.

**Comment by fittotweet** [comment]
(total noob here (first comment ever!)).  I just ran into this as well.  I had to manually create a `next.config.js` file w target set to 'serverless' and run 'npx next build' to create the missing files/folders in the .next folder.   Am not getting that plugin error now.

**Comment by lindsaylevine** [comment]
@mrpaulphan @olegrjumin are you still experiencing this issue when using next-on-netlify? if so, can you provide these details about your setup?

1. netlify.toml
2. build command (if your toml build command is an npm script pointing to the actual command)

seems like @fittotweet's issue was resolved by using the correct configuration :)

i don't think it's possible to not have .next/static if you're running `next build` at any point in your build/deploy process.
