### ISSUE TITLE
Missing `pages-manifest.json`

### ISSUE THREAD

**Issue by ehmicky** [netlify/next-on-netlify#136]
Some sites seem to be missing a `pages-manifest.json`, which makes the build fail.

Link to [Bugsnag error](https://app.bugsnag.com/netlify/netlify-build/errors/5fc711325228df0018b2ae7e).

Build logs:

```
9:51:21 PM: ────────────────────────────────────────────────────────────────
9:51:21 PM:   3. onBuild command from @netlify/plugin-nextjs                
9:51:21 PM: ────────────────────────────────────────────────────────────────
9:51:21 PM: ​
9:51:21 PM: ** Running Next on Netlify package **
9:51:21 PM: 🚀 Next on Netlify 🚀
9:51:21 PM: 🌍️ Copying public/ folder to /opt/build/repo
9:51:21 PM: 💼 Copying static NextJS assets to /opt/build/repo
9:51:21 PM: ​
9:51:21 PM: ────────────────────────────────────────────────────────────────
9:51:21 PM:   Plugin "@netlify/plugin-nextjs" internal error                
9:51:21 PM: ────────────────────────────────────────────────────────────────
9:51:21 PM: ​
9:51:21 PM:   Error message
9:51:21 PM:   Error: .next/serverless/pages-manifest.json: ENOENT: no such file or directory, open '.next/serverless/pages-manifest.json'
9:51:21 PM: ​
9:51:21 PM:   Plugin details
9:51:21 PM:   Package:        @netlify/plugin-nextjs
9:51:21 PM:   Version:        1.0.3
9:51:21 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
9:51:21 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
9:51:21 PM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
9:51:21 PM: ​
9:51:21 PM:   Error location
9:51:21 PM:   In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
9:51:21 PM:       at Object.openSync (fs.js:458:3)
9:51:21 PM:       at Object.readFileSync (fs.js:360:35)
9:51:21 PM:       at readFileSync (/opt/build/repo/.netlify/plugins/node_modules/jsonfile/index.js:50:22)
9:51:21 PM:       at getPagesManifest (/opt/build/repo/.netlify/plugins/node_modules/next-on-netlify/lib/helpers/getPagesManifest.js:6:20)
9:51:21 PM:       at Object.<anonymous> (/opt/build/repo/.netlify/plugins/node_modules/next-on-netlify/lib/pages/api/pages.js:8:23)
9:51:21 PM:       at Module._compile (internal/modules/cjs/loader.js:1133:30)
9:51:21 PM:       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
9:51:21 PM:       at Module.load (internal/modules/cjs/loader.js:977:32)
9:51:21 PM:       at Function.Module._load (internal/modules/cjs/loader.js:877:14)
9:51:21 PM:       at Module.require (internal/modules/cjs/loader.js:1019:19)
```

[Example git commit](https://github.com/mitchwongho/bookfriends/commit/5cd0f587f919257be28362f153d1a637082b7a72)

**Comment by lindsaylevine** [comment]
odd. thanks for reporting!!!!!
