### ISSUE TITLE
Failure when the publish directory is `public`.

### ISSUE THREAD

**Issue by ehmicky** [netlify/next-on-netlify#137]
When the publish directory is `public`, the following line of code fails:

https://github.com/netlify/next-on-netlify/blob/ae79eb03feb2c9f86ae4823d3bb1f1c070883281/lib/steps/copyPublicFiles.js#L12

This is because we try to copy `./public/` to `./public/`.

[Bugsnag error](https://app.bugsnag.com/netlify/netlify-build/errors/5fc902ded8ad01001895be48)

[Build logs](https://app.netlify.com/sites/wilshirelaw/deploys/5ff4ed13f9cccf2953eb4dc9):

```
11:51:12 PM: ────────────────────────────────────────────────────────────────
11:51:12 PM:   4. onBuild command from @netlify/plugin-nextjs                
11:51:12 PM: ────────────────────────────────────────────────────────────────
11:51:12 PM: ​
11:51:12 PM: ** Running Next on Netlify package **
11:51:12 PM: 🚀 Next on Netlify 🚀
11:51:12 PM: 🌍️ Copying public/ folder to public
11:51:12 PM: ​
11:51:12 PM: ────────────────────────────────────────────────────────────────
11:51:12 PM:   Plugin "@netlify/plugin-nextjs" internal error                
11:51:12 PM: ────────────────────────────────────────────────────────────────
11:51:12 PM: ​
11:51:12 PM:   Error message
11:51:12 PM:   Error: Source and destination must not be the same.
11:51:12 PM: ​
11:51:12 PM:   Plugin details
11:51:12 PM:   Package:        @netlify/plugin-nextjs
11:51:12 PM:   Version:        1.0.3
11:51:12 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
11:51:12 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
11:51:12 PM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
11:51:12 PM: ​
11:51:12 PM:   Error location
11:51:12 PM:   In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
11:51:12 PM:       at Object.checkPathsSync (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/util/stat.js:51:11)
11:51:12 PM:       at copySync (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
11:51:12 PM:       at copyPublicFiles (/opt/build/repo/.netlify/plugins/node_modules/next-on-netlify/lib/steps/copyPublicFiles.js:12:3)
11:51:12 PM:       at nextOnNetlify (/opt/build/repo/.netlify/plugins/node_modules/next-on-netlify/index.js:23:3)
11:51:12 PM:       at onBuild (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/index.js:82:5)
11:51:12 PM:       at async Object.run (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/run.js:19:3)
11:51:12 PM:       at async handleEvent (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/main.js:36:38)
11:51:12 PM:       at async process.<anonymous> (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/ipc.js:103:16)
```

**Comment by lindsaylevine** [comment]
great catch!!!!!! thanks for opening <3 @ehmicky
